server:
  port: 9527
spring:
  application:
    name: cloud-gateway
eureka:
  client:
#    注册到注册中心
    register-with-eureka: true
#    地址
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka